apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-library-staging
  namespace: colossus-home-library-staging
  labels:
    app: home-library-staging
    managed-by: colossus
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: home-library-staging
  template:
    metadata:
      labels:
        app: home-library-staging
    spec:
      hostAliases:
        - ip: "192.168.50.250"
          hostnames:
            - "ubuntu.desmana-truck.ts.net"
      containers:
        - name: app
          image: ubuntu:30500/home-library-staging:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
          envFrom:
            - secretRef:
                name: app-secrets
                optional: true
